


-- HAVERÁ DOIS TIPOS DE AMOSTRA:
	-- 1) UMA ATÉ O NÍVEL MUNICIPIO, PARA CRUZAR COM IGM E OUTRAS BASES POR 'COD_MUNIC_IBGE', PARA ANÁLISE DO DIRECIONAMENTO DE POLÍTICAS PÚBLICAS (COMPARAR COM MÉTRICAS DE POPULAÇÃO, IDH, IVS, SEG, RENDAPERCAPTA, PIB,....)

  -- 2) OUTRA ATÉ O NÍVEL DO FORNECEDOR, PARA CRUZAR COM BASES DE CNPJ, SOCIOS, FUNCIONÁRIOS, PARLAMENTAR, SERVIDORES (EXE, JUD, LEG, MUN, EST), PARENTESCO,

-- DEFINIÇÕES PARA DIMENSÃO TEMPO: mês / ano (proposta, convenio, empenho, pagamento) -- SERIA INTERESSANTE TAMBÉM PEGAR AS DATAS DO REPASSE

-- CRIAR CAMPOS DERIVADOS PARA AGRUPAMENTO (T/F - 0/1) - FORNECEDOR É PF OU PJ ? / (VALOR DO REPASSE > VALOR EMPENHADO) ? / (VALOR INICIAL < VALOR FINAL) ?

-- FILTRAR AMOSTRA:
 	--.. APENAS CONVÊNIOS COM VALORES MAIORES QUE R$100.000 OU APENAS PARA A OSICPs ?

-- JUNTAR COM A AMOSTRA DA IGM (MUNIC_PROPONENTE = MUNIC_igm)

--

﻿-- relacionando proposta + convenio + emenda + empenho + pagamento (faltam outras variáveis importantes)
select
-- DIMENSÕES DE ANÁLISE
	"Vincular UF <> Região" as REGIAO,-- Seguir a nível de bairro (base IBGE)
   pr.UF_PROPONENTE,
  pr.MUNIC_PROPONENTE,
  pr.COD_MUNIC_IBGE,
	pr.COD_ORGAO,
	pr.DESC_ORGAO,
  pr.MODALIDADE,
  pr.NATUREZA_JURIDICA,
	pr.IDENTIF_PROPONENTE,
	pr.NM_PROPONENTE,
	pr.SIT_PROPOSTA,

	cv.SIT_CONVENIO,
	cv.SUBSITUACAO_CONV,
	cv.SITUACAO_PUBLICACAO,

  em.COD_PROGRAMA_EMENDA,
	em.NR_EMENDA,
	em.NOME_PARLAMENTAR,
	em.BENEFICIARIO_EMENDA,
	em.TIPO_PARLAMENTAR,

	pg.IDENTIF_FORNECEDOR,
	pg.NOME_FORNECEDOR,
	pg.TP_MOV_FINANCEIRA,
	pg.DESC_DL,(DIÁRIAS, FOLHA PGTO...) -- SEPARAR EM DOIS DOMÍNIOS: SERVIÇOS, OBRAS, AUTONOMO, ETC...

	-- INDICADORES (S/N, T/F)
	cv.IND_ASSINADO,
	cv.IND_OPERA_OBTV,
	em.IND_IMPOSITIVO,


	-- DIMENSÃO TEMPO
		pr.DIA_PROPOSTA,
		cv.DIA_ASSIN_CONV,
		cv.DIA_PUBL_CONV, cv.DIA_INIC_VIGENC_CONV, cv.DIA_FIM_VIGENC_CONV, cv.DIAS_PREST_CONTAS, cv.DIA_LIMITE_PREST_CONTAS,
    YEAR(ep.DATA_EMISSAO) AS ANO_EMPENHO,
		pg.DATA_PAG,

-- VALORES DE FATO (AGREGAÇÕES)

  pr.ID_PROPOSTA,
  pr.NR_PROPOSTA,
	pr.VL_GLOBAL_PROP,
	pr.VL_REPASSE_PROP,
	pr.VL_CONTRAPARTIDA_PROP,

	cv.NR_CONVENIO,
	cv.QTDE_CONVENIOS,
	cv.QTD_TA,
	cv.QTD_PRORROGA,

	(cv.VL_EMPENHADO_CONV / cv.VL_DESEMBOLSADO_CONV) -- TEM QUE SER UM VALOR NO MÁXIMO = 1, POIS SE TIVER + DESEMB QUE EMPEN, É UM ERRO DE NEGÓCIO
  -- (%) RELAÇÃO DO VL_CONTRAPARTIDA_CONV / VL_REPASSE_CONV  -- SERÁ QUE ESSE INDICADOR PODE GERAR ALGUM PADRÃO PARA DETECÇÃO DE ANOMALIAS ?
	-- VERIFICAR RELAÇÕES ENTRE VARIÁVEIS NUMÉRICAS NA BUSCA DE PADRÕES E POSSIBILIDADES DE RANKINGS

	cv.VL_GLOBAL_CONV,
	cv.VL_REPASSE_CONV,
	cv.VL_CONTRAPARTIDA_CONV,
	cv.VL_SALDO_REMAN_TESOURO,
	cv.VL_SALDO_REMAN_CONVENENTE,
	cv.VL_RENDIMENTO_APLICACAO,
	cv.VL_INGRESSO_CONTRAPARTIDA,
	cv.VL_SALDO_CONTA,

	sum(em.VALOR_REPASSE_PROPOSTA_EMENDA) as VALOR_REPASSE_PROPOSTA_EMENDA,
	em.VALOR_REPASSE_EMENDA,

	count(ep.ID_EMPENHO) as qt_empenhos,
	-- ep.TIPO_NOTA -- ep.DESC_TIPO_NOTA (DEPENDENDO DO TIPO, O VALOR SERÁ NEGATIVO [ANULAÇÃO] ), ep.DESC_SITUACAO_EMPENHO,
	-- DEPENDERÁ DO TIPO DA NE .. ep.VALOR_EMPENHO,

	COUNT(pg.NR_MOV_FIN) as qt_mov_fin,
	COUNT(pg.NR_DL) as qt_doc_liq,
  sum(pg.VL_PAGO) as vl_pago_fornecedor

from convenio cv, proposta pr, emenda em, empenho ep, pagamento pg
where cv.id_proposta = pr.id_proposta
and pr.id_proposta = em.id_proposta
and cv.nr_convenio = ep.nr_convenio
and pg.nr_convenio = cv.nr_convenio
and cv.INSTRUMENTO_ATIVO = 'SIM';

GROUP BY
-- DIMENSÕES DE ANÁLISE
	"Vincular UF <> Região" as REGIAO,-- Seguir a nível de bairro (base IBGE)
   pr.UF_PROPONENTE,
  pr.MUNIC_PROPONENTE,
  pr.COD_MUNIC_IBGE,
	pr.COD_ORGAO,
	pr.DESC_ORGAO,
  pr.MODALIDADE,
  pr.NATUREZA_JURIDICA,
	pr.IDENTIF_PROPONENTE,
	pr.NM_PROPONENTE,
	pr.SIT_PROPOSTA,

	cv.SIT_CONVENIO,
	cv.SUBSITUACAO_CONV,
	cv.SITUACAO_PUBLICACAO,

  em.COD_PROGRAMA_EMENDA,
	em.NR_EMENDA,
	em.NOME_PARLAMENTAR,
	em.BENEFICIARIO_EMENDA,
	em.TIPO_PARLAMENTAR,

	pg.IDENTIF_FORNECEDOR,
	pg.NOME_FORNECEDOR,
	pg.TP_MOV_FINANCEIRA,
	pg.DESC_DL,(DIÁRIAS, FOLHA PGTO...) -- SEPARAR EM DOIS DOMÍNIOS: SERVIÇOS, OBRAS, AUTONOMO, ETC...

	-- INDICADORES (S/N, T/F)
	cv.IND_ASSINADO,
	cv.IND_OPERA_OBTV,
	em.IND_IMPOSITIVO
